version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: price_alert_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5433:5433"  # Mapping your local port 5433 to the container's port 5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:qwerty@db:5432/price_alert_db


#version: '3'
#services:
#  api:
#    build:
#      context: ./price_alert
#      dockerfile: Dockerfile
#      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - static_volume:/price_alert/staticfiles/
#      - media_volume:/price_alert/mediafiles/
#    expose:
#      - 80
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    ports:
#      - 80:80
#    volumes:
#      - static_volume:/price_alert/staticfiles/
#      - media_volume:/price_alert/mediafiles/
#volumes:
#  static_volume:
#  media_volume: